development:
  cloud_name: "adrianobocoli"
  api_key: "271162645475657"
  api_secret: "8vxDJOWUd5X8T1mDsjMMUZQoxEw"

production:
  cloud_name: "adrianobocoli"
  api_key: "271162645475657"
  api_secret: "8vxDJOWUd5X8T1mDsjMMUZQoxEw"
